title: "David Scholtz"
logo: /portfolio_images/profile-square.jpg
description: >
  Welcome to my personal website and portfolio, where you can explore my journey as a data analyst. Feel free to browse through my projects, view my resumé, and get in touch to discuss potential collaborations or opportunities. I'm excited to share my journey with you!
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
