title: 'David Scholtz'
logo: /portfolio_images/profile-round.png
description: >
  I'm a freelance data analyst with experience using statistics, machine learning algorithms, and interactive dashboards to solve business problems. I have a critical understanding of business needs and the ability to creatively apply data analytic solutions that are accessible and actionable for end users. I'm excited to share my journey in analytics with you! 
  <br>
  <strong>Contact me</strong>
  <br>

<a href="mailto:davidianscholtz@gmail.com" style="display: inline-block;">
   <img src="./portfolio_images/Gmail_icon_(2020).svg" style="width: 25px; height: auto;" />
   Email
</a>
  
  <strong>Email:</strong> davidianscholtz [at] gmail.com 
  <br>
  <a href="https://www.linkedin.com/in/davidianscholtz/" style="display: inline-block;">
    <img src="./portfolio_images/LinkedIn_icon.svg" style="width: 25px; height: auto;" />
    LinkedIn
  </a> 
  <br>
  <a href="https://github.com/DStrix66/" style="display: inline-block;">
    <img src="./portfolio_images/github-mark.svg" style="width: 25px; height: auto;" />
    GitHub
  </a> 
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
