title: 'David Scholtz'
logo: /portfolio_images/profile-round.png
description: >
  I'm a freelance data analyst with experience using statistics, machine learning algorithms, and interactive dashboards to deliver accessible and actionable data solutions. 
  <br><br>
  <strong>Get in touch</strong>
  <br><br>
  <a href="mailto:davidianscholtz@gmail.com" style="display: inline-block;">
    <img src="./portfolio_images/Gmail_icon_(2020).svg" style="width: 25px; height: auto;" />
    Email
  </a>  
  <br>
  <a href="https://www.linkedin.com/in/davidianscholtz/" style="display: inline-block;">
    <img src="./portfolio_images/LinkedIn_icon.svg" style="width: 25px; height: auto;" />
    LinkedIn
  </a> 
  <br>
  <a href="https://github.com/DStrix66/" style="display: inline-block;">
    <img src="./portfolio_images/github-mark.svg" style="width: 25px; height: auto;" />
    GitHub
  </a> 
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
