title: "David Scholtz"
logo: /portfolio_images/profile-round.png
description: >
  Welcome to my website and portfolio. Feel free to browse through my projects, view my resumé, and get in touch to discuss potential collaborations or opportunities. I'm excited to share my journey with you!
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
